DROP DATABASE IF EXISTS csc648_team6;
CREATE DATABASE csc648_team6;

USE csc648_team6;

CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	create_date DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id)
);

CREATE TABLE postings (
    id int(11) NOT NULL AUTO_INCREMENT,
    user_id INT NULL,
    location VARCHAR(100) DEFAULT NULL,
    postType VARCHAR(20) DEFAULT NULL,
    postStatus VARCHAR(20) DEFAULT NULL,
    imageUpload VARCHAR(255) DEFAULT NULL,
    longitude DECIMAL(25,15) NOT NULL DEFAULT 0.000000000000000,
    latitude DECIMAL(25,15) NOT NULL DEFAULT 0.000000000000000,
    postings_created_date DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
); 